#!/bin/sh
set -a
source "$(dirname "$0")/.env"
set +a

export DATACONTRACT_S3_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
export DATACONTRACT_S3_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
export DATACONTRACT_S3_SESSION_TOKEN="$AWS_SESSION_TOKEN"
export DATACONTRACT_S3_REGION="eu-west-1"
